♻️  refactor: Refactor the code for wttr

diff --git a/.local/bin/wttr b/.local/bin/wttr
--- a/.local/bin/wttr
+++ b/.local/bin/wttr
@@ -1,28 +1,28 @@
 #!/bin/bash
 #
-#Author(original) : Amirreza Firoozi, Carsten Brueggenolte
-#Author(current) : hahapigs
-#name : wttr
-#Update 1.30: change config dir to ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr to go in line with other configuration files
-#Update 1.30: changed default city filename to 'default-city.txt'
-#Update 1.40: add v2.wttr.in feature and did some clean up
-#Update 1.41: add spaces in between city and url
-#Update 1.42: reverse changes with the space between url and city
-#Update 1.50: add v3.wttr.in - thanks to dok-ock for the inspiration and the fixes
-#Update 1.51: update about section and add it to the help screen
-#Update 1.52: move help and about into their own variables for better maintanance
-#Update 1.53: add a parameters '-t' current forecast and '-n' current weather
-#Update 1.54: spell check and added some optional parameters for -help, -today, -now
-#Update 1.55: refactor the '-i' parameters in the curl installation code
+# author: hahapigs
+#
+# wttr - A command-line weather information client for wttr.in
+# This script provides a convenient way to query weather information
+# from wttr.in service with various formatting options.
 
-wttr_ver="1.55_2025-04-06" #define script version
+set -e
 
-GITHUB_REPO_URL="https://github.com/cblte/bash-script-wttr"
-URL="https://wttr.in/"
-URLv2="https://v2.wttr.in/"
-URLv3="https://v3.wttr.in/"
+# version
+wttr_ver="0.01_2025-04-11"
+# github
+GITHUB_REPO_URL="https://github.com/hahapigs/work-theme"
 
-About()
+# Configuration file paths
+CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/wttr"
+DEFAULT_CITY_FILE="${CONFIG_DIR}/default-city.txt"
+
+# API base URL configuration
+URL_v1="https://wttr.in"    # Standard wttr.in endpoint with full features
+URL_v2="https://v2.wttr.in" # Alternative v2 endpoint with different formatting
+URL_v3="https://v3.wttr.in" # Latest v3 endpoint with enhanced features
+
+show_about()
 {
 echo -e "
 About the
@@ -33,209 +33,251 @@ About the
 ██║███╗██║   ██║      ██║   ██╔══██╗   ██║██║╚██╗██║
 ╚███╔███╔╝   ██║      ██║   ██║  ██║██╗██║██║ ╚████║
  ╚══╝╚══╝    ╚═╝      ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝╚═╝  ╚═══╝
-                      script by Carsten Brueggenolte
+                                  script by hahapigs
 
 
 This is a simple bash script to check weather condition
 with the help of wttr.in. The script 'wttr' is under GPL3 License.
 
 Source is available on Github: $GITHUB_REPO_URL
-
-Big THANK YOU goes to
-    - 'Amirreza Firoozi' (https://github.com/AmirrezaFiroozi/wttr)
-      for creating the initial script
-    - 'doc-ock' (https://github.com/doc-ock/) for the idea to add
-      version 3 of wttr.in and some other useful parameters.
 "
 }
 
-Help()
-{
-echo -e "
-Write 'wttr {your+city+name}' to check the  weather condition of your city.
-Surround city name with single- or double-quotes if city name contains more than one word.
-You can also put a '+' (plus-sign) in beetween words when you do not want to surround with quotes.
-
-Examples:
-   wttr cologne
-   wttr \"Den Haag, Netherland\"
-   wttr Den+Haag
-   wttr \"Den Haag Street, South Africa\"
-   wttr New+York
-
-You can type 'wttr' only if you have defined a standard city.
-
-Parameters:
-    -a show some information about this script
-    -h for some help (this page)
-    -hh for the official wttr.in/:help page
-    -i to install curl which is necessary for script to run correctly
-    -m for photo of moon
-    -n show current weather only
-    -rm to remove the script :(
-    -sdef to define a city as your default city
-    -t show today's forecast
-    -v show script version
-    -v2 to fetch different weather report view for the standard city
-    -v2 {your city name} to fetch different weather report view for city mentioned
-    -v3 {your city name} to fetch an in-terminal graphic for the given region.
-
-Hint:
-     When using '-v3' you do not need to add the '.sxl' to the
-     end of the region/city name. The script will add it automatically.
-
-Any bugs? Any suggestions? Contact information at https://cbrueggenolte.de/impressum
-"
+# Display help information
+show_help() {
+    echo -e "\033[1mwttr - Command-line weather client for wttr.in\033[0m"
+    echo
+    echo -e "\033[1mUsage:\033[0m"
+    echo -e "  wttr [OPTIONS]"
+    echo -e "  wttr CITY [FORMAT] [LANG]"
+    echo
+    echo -e "\033[1mOptions:\033[0m"
+    echo -e "  \033[1m-A, --about\033[0m           About"
+    echo -e "  \033[1m-c, --city CITY\033[0m       Specify the city or location to query"
+    echo -e "  \033[1m-f, --format NUMBER\033[0m   Specify output format (number 1-4 or placeholders)"
+    echo -e "  \033[1m-h, --help\033[0m            Display this help information"
+    echo -e "  \033[1m-l, --lang LANGUAGE\033[0m   Set language (zh-cn/en-us)"
+    echo -e "  \033[1m-r, --remove\033[0m          Remove configuration files"
+    echo -e "  \033[1m--sdef CITY\033[0m           Set default city for future queries"
+    echo -e "  \033[1m--tmux \033[0m               Supports tmux"
+    echo -e "  \033[1m-v2\033[0m                   Use v2.wttr.in API endpoint"
+    echo -e "  \033[1m-v3\033[0m                   Use v3.wttr.in API endpoint"
+    echo -e "  \033[1m-v, --version\033[0m         Show current version"
+    echo -e "  \033[1m-V, --view [0|1|2]\033[0m    Set the view mode for weather display"
+    echo
+    echo -e "\033[1mView Modes:\033[0m"
+    echo -e "  \033[1m--view 0\033[0m:             Only current weather"
+    echo -e "  \033[1m--view 1\033[0m:             Current weather + today's forecast"
+    echo -e "  \033[1m--view 2\033[0m:             Current weather + today's + tomorrow's forecast"
+    echo
+    echo -e "\033[1mExamples:\033[0m"
+    echo -e "  wttr Beijing          # Get weather for Beijing with default format"
+    echo -e "  wttr -c Shanghai -v2  # Use v2 API for Shanghai weather"
+    echo -e "  wttr --view 0         # Get single-line weather for default city"
+    echo -e "  wttr -f 3             # Use built-in format number 3"
+    echo -e "  wttr -l zh-cn         # Get weather in English"
+    echo -e "  wttr --sdef Beijing   # Set Beijing as your default city"
+    echo -e "  wttr                  # Get weather for your default city"
+    echo
+    echo -e "\033[1mConfiguration File Location:\033[0m"
+    echo -e "  \${XDG_CONFIG_HOME:-\${HOME}/.config}/wttr/default-city.txt"
+    echo
+    echo -e "\033[1mSpecial URLs:\033[0m"
+    echo -e "  curl https://wttr.in/:help   # show wttr.in page"
 }
 
-# ------------------------
-# ----- Script starts here
-# ------------------------
+# Get default city (without auto-creating directory)
+get_default_city() {
+    if [[ -f "$DEFAULT_CITY_FILE" ]]; then
+        local city=$(head -n 1 "$DEFAULT_CITY_FILE" | tr -d '[:space:]')
+        if [[ -n "$city" ]]; then
+            echo "$city"
+            return
+        fi
+    fi
+    echo -e "\033[31mError: Default city not set, please use --sdef to set a default city first\033[0m" >&2
+    exit 1
+}
 
-# Check if a standard city has been set
-if [ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/wttr/default-city.txt" ];then #check if user set default city or not . if user did load it to variable def
-    cd ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr
-    def=$(cat default-city.txt)
-elif [ ! -d ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr ];then #if he/she didn`t make a blank file
-    mkdir "${XDG_CONFIG_HOME:-${HOME}/.config}/wttr"  2>/dev/null
-    cd ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr
-    echo "" > default-city.txt
-    def=""
+# Set default city (only creates directory at this time)
+set_default_city() {
+    mkdir -p "$CONFIG_DIR"
+    echo "$1" > "$DEFAULT_CITY_FILE"
+    echo -e "Default city set to: \033[1m$1\033[0m"
+    echo -e "Configuration file location: \033[1m$DEFAULT_CITY_FILE\033[0m"
+}
+
+# Validate language parameter
+validate_lang() {
+    case "$1" in
+        zh-cn|en-us) return 0 ;;
+        *)
+            echo -e "Error: Unsupported language \033[1m$1\033[0m, only zh-cn or en-us are supported" >&2
+            exit 1
+        ;;
+    esac
+}
+
+# Validate view parameter
+validate_view() {
+    case "$1" in
+        0|1|2) return 0 ;;
+        *)
+            echo -e "Error: Invalid view parameter \033[1m$1\033[0m, only 0/1/2 are supported" >&2
+            exit 1
+        ;;
+    esac
+}
+
+# Validate format placeholders
+validate_format() {
+    local format="$1"
+
+    # Validate numeric format options (1-4)
+    if [[ "$format" =~ ^[1-4]$ ]]; then
+        return 0
+    fi
+
+    echo -e "Error: Format must be \033[1m1/2/3/4\033[0m" >&2
+    exit 1
+}
+
+# Remove default configuration
+remove() {
+    if [[ -d "$CONFIG_DIR" ]]; then
+        rm -rf "$CONFIG_DIR"
+        echo -e "\033[1mConfiguration directory removed: $CONFIG_DIR\033[0m"
+    else
+        echo -e "\033[1mConfiguration directory not found\033[0m"
+    fi
+    echo -e "\033[32mUninstallation complete\033[0m"
+    exit 0
+}
+
+# Parameter parsing
+city=""
+view=""
+format=""
+lang=""
+__tmux=""
+url="$URL_v1"  # Default to standard API
+positional=()
+
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        -A|--about)
+            command -v lolcat &>/dev/null && show_about | lolcat || show_about
+            exit 0
+        ;;
+        -h|--help)
+            show_help
+            exit 0
+        ;;
+        -v|--version)
+            echo -e "wttr version is: $wttr_ver"
+            exit 0
+        ;;
+        -c|--city)
+            if [[ -z "$2" ]]; then
+                echo -e "Error: Please provide a city name" >&2
+                show_help
+                exit 1
+            fi
+            city="$2"
+            shift 2
+        ;;
+        -V|--view)
+            if [[ -z "$2" ]]; then
+                echo -e "Error: Please provide a view parameter" >&2
+                show_help
+                exit 1
+            fi
+            validate_view "$2"
+            view="$2"
+            shift 2
+        ;;
+        -f|--format)
+            if [[ -z "$2" ]]; then
+                echo -e "Error: Please provide a format parameter" >&2
+                show_help
+                exit 1
+            fi
+            validate_format "$2"
+            format="$2"
+            shift 2
+        ;;
+        -l|--lang)
+            if [[ -z "$2" ]]; then
+                echo -e "Error: Please provide a language parameter" >&2
+                show_help
+                exit 1
+            fi
+            validate_lang "$2"
+            lang="$2"
+            shift 2
+        ;;
+        -v2)
+            url="$URL_v2"
+            shift
+        ;;
+        -v3)
+            url="$URL_v3"
+            shift
+        ;;
+        --sdef)
+            if [[ -z "$2" ]]; then
+                echo -e "Error: Please provide a default city name" >&2
+                show_help
+                exit 1
+            fi
+            set_default_city "$2"
+            exit 0
+        ;;
+        --tmux)
+            __tmux=true
+            format=3
+            shift
+        ;;
+        -r|--remove)
+            remove
+        ;;
+        -*)
+            echo -e "Error: Unknown option \033[1m$1\033[0m" >&2
+            show_help
+            exit 1
+        ;;
+        *)
+            positional+=("$1")
+            shift
+        ;;
+    esac
+done
+
+# Process positional parameters
+if [[ ${#positional[@]} -gt 0 ]]; then
+    if [[ -z "$city" ]]; then
+        city="${positional[0]}"
+    else
+        echo -e "Error: Excess parameters '${positional[*]}'" >&2
+        show_help
+        exit 1
+    fi
 fi
 
-# Print out some help if no arguments provided and no standard city been set
-if [ "$#" == "0" ] && [ "$def" == "" ];then
-    echo -e "You have not entered any parameters and no standard city set yet.\nNeed help? try 'wttr -h'"
-elif [ "$#" -gt "2" ];then
-    echo -e "too many parameters. \nNeed help? try 'wttr -h'"
-else
-    case $1 in
-    # currently doesn't work: upgrade. There is some permissions problem
-    # "-u" | "-upgrade")
-	# echo -e "Checking for upgrades..."
-    	# git clone $GITHUB_REPO_URL /tmp/wttr
-	# bash /tmp/wttr/installer.sh
-    # ;;
-    "-a") # about
-        About
-    ;;
-    "-h" | "-help") #showing help
-        Help
-    ;;
-    "-hh")
-        curl https://wttr.in/:help
-    ;;
-    "-i")
-        if command -v curl &>/dev/null ; then
-            echo -e "Since you have previously installed curl, you can upgrade it by running brew upgrade curl."
-        else
-            echo -e "Homebrew: brew install curl"
-            # sudo apt install curl
-        fi
-    ;;
-    "-m")
-        curl http://wttr.in/moon
-    ;;
-    "-n" | "-now")
-        echo -e "Fetching current weather"
-        if [ "$#" == "2" ];then
-            city="$2"
-            city=${city// /+}
-            city=${city//[^a-zA-Z0-9+]}
-            curl $URL"$city?0n"
-        else
-            curl $URL"$def?0n"
-        fi
-        cd $HOME
-    ;;
-    "-rm")
-        read -p "Do you really want to remove wttr? (y/n)" response
-        if [ "$response" == "y" ];then
-            cd /usr/bin
-            sudo rm -R "wttr"    2>/dev/null
-            if [ -d "${XDG_CONFIG_HOME:-${HOME}/.config}/wttr" ];then
-                sudo rm -d "${XDG_CONFIG_HOME:-${HOME}/.config}/wttr" 2>/dev/null
-            fi
-            echo -e "Script has deleted :("
-        else
-            echo -e "Opration canceled"
-        fi
-    ;;
-    "-sdef") # set the default city
-        if [ ! -d ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr ];then
-            cd $HOME
-            mkdir -p ".config/wttr" 2>/dev/null
-        fi
-        if [ "$#" == "2" ];then
- 	        cd ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr
-            echo "$2" > default-city.txt
-	        echo -e ""
-            echo -e "Done. Set '$2' as your default city. You can check its weather condition by typing only 'wttr' now :)"
-        else
-            read -p "Enter your city name to set as the default city (example : cologne) : " def
-            # replacing spaces with + signes and removing non wanted chars
-            def=${def// /+}
-            def=${def//[^a-zA-Z0-9+]}
-            if [ "$def" == "" ] && [ "$#" -ne "2" ];then
-                echo "you did NOT enter anything ..."
-            else
-                cd ${XDG_CONFIG_HOME:-${HOME}/.config}/wttr
-                echo $def > default-city.txt
-	            echo -e ""
-                echo -e "Done. Set '$def' as your default city. You can check its weather condition by typing only 'wttr' now :)"
-            fi
-        fi #end of the second if
-    ;;
-    "-t" | "-today")
-        echo -e "Fetching today's forecast"
-        if [ "$#" == "2" ];then
-            city="$2"
-            city=${city// /+}
-            city=${city//[^a-zA-Z0-9+]}
-            curl $URL"$city?1n"
-        else
-            curl $URL"$def?1n"
-        fi
-        cd $HOME
-    ;;
-    "-v")
-        echo -e "wttr_VERSION is: "$wttr_ver" "
-    ;;
-    "-v2")
-        echo -e "Fetching v2 of wttr.in"
-        if [ "$#" == "2" ];then
-            city="$2"
-            city=${city// /+}
-            city=${city//[^a-zA-Z0-9+]}
-            curl $URLv2"$city"
-        else
-            curl $URLv2"$def"
-        fi
-        cd $HOME
-    ;;
-    "-v3")
-        echo -e "Fetching v3 of wttr.in"
-        if [ "$#" == "2" ];then
-           city="$2"
-           city=${city// /+}
-           city=${city//[^a-zA-Z0-9+]}
-           curl $URLv3"$city".sxl
-        else
-           curl $URLv3"$def".sxl
-        fi
-            cd $HOME
-    ;;
-    "")
-        cd $HOME
-        curl $URL"$def"
-    ;;
-    *)
-
-    city=$1
+# Get default city (if not specified and needed)
+if [[ -z "$city" ]]; then
+    city=$(get_default_city)
     city=${city// /+}
     city=${city//[^a-zA-Z0-9+]}
-    curl $URL"$city"
-
-    ;;
-  esac
 fi
+
+# Build API request parameters array
+params=()
+[[ -n "$view" ]] && params=("$view")              # Add view parameter if specified
+[[ -n "$format" ]] && params+=("format=$format")  # Add format parameter if specified
+[[ -n "$lang" ]] && params+=("lang=$lang")        # Add language parameter if specified
+params+=("F")  # Add 'F' as a default parameter (Fahrenheit to Celsius conversion)
+
+# Call the API
+[[ $__tmux ]] && curl -f -s -m 2 ${url}/${city}?$(IFS='&'; echo "${params[*]}") && exit 0
+curl -s ${url}/${city}?$(IFS='&'; echo "${params[*]}")
